config/routes.rb
Rails.application.routes.draw do
  apipie
  mount RailsAdmin::Engine => '/superadmin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  post '/login' => 'home#login', as: :login

  delete '/logout' => 'dashboard#logout', as: :logout
  get '/dashboard' => 'dashboard#index', as: :dashboard
  get '/muwashafat' => 'muwashafat#index', as: :muwashafats
  patch '/muwashafat/:id' => 'muwashafat#update', as: :update_muwashafat

  get '/yaumiyah' => 'yaumiyah#index', as: :yaumiyah
  post '/yaumiyah/report' => 'yaumiyah#report', as: :yaumiyah_report

  namespace :api do
    namespace :v1, format: :json do
      resources :token, only: [:create, :destroy]
      resources :muwashafat, only: [:index, :update]
      resources :users, only: [:show, :update]
      resources :yaumiyah, only: [:index, :create, :update]
      resources :reports, only: [:index]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mutabaah</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8" />
    <meta content="IE=edge" http-equiv="X-UA-Compatible" />
    <meta content="width=device-width, initial-scale=1" name="viewport" />
  </head>

  <body>
    <% if flash[:notice] %>
      <div class='notice-message'>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class='alert-message'>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <% if session[:current_user_id] %>
      <div><%= "Login sebagai #{current_user.name}"%></div>
      <div class='top-nav'>
        <ul>
          <li><%= link_to 'Muwashafat', muwashafats_path %></li>
          <li><%= link_to 'Yaumiyah', yaumiyah_path %></li>
          <li><%= link_to 'Logout', logout_path, method: :delete %></li>
        </ul>
      </div>
    <% end %>

    <div class='wrapper'>
      <%= yield %>
    </div>
  </body>
</html>